### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by anseljh** [rxnda/rxnda-forms#2]
I reviewed B-1W-B2I in some detail and found a few typos. I think they are probably common to other forms, so I'm opening the issue here.

* 4(e): Insert "shall" in the first sentence: "Receiving Party *shall* not break"
* 4(g)(i): In the second sentence, insert "a": "...to afford Disclosing Party *a* practical chance"
* 4(g)(i): In the last sentence, replace "assistant" with "assistance"

**Comment by kemitchell** [comment]
@anseljh: Many thanks! I'll have a look ASAP.

Open PRs wherever you find convenient.

**Comment by anseljh** [comment]
I wasn't sure where to open a PR for changes across multiple forms, but if you can point me in the right direction, I'm happy to do it.

**Comment by kemitchell** [comment]
As you probably guessed, all these forms started out as outputs of a common template. Unfortunately, one repository made it difficult to version the forms independently, and also more difficult to find and download prerendered copies for those unfamiliar with building "from source".

I know the forms best, and have the tooling to take issues here on rxnda-forms and fan them out to the various form-specific repos. For now, issues here on rxnda-forms are best.

**Comment by kemitchell** [comment]
@anseljh: I've just pushed commits across all relevant repositories picking all three nits.  I will review this evening and release new editions.

Thanks again so much for opening this issue. Is there some way that I can thank you---publicly, privately, or both?

**Comment by kemitchell** [comment]
Sorry. Reopening until we find out how to give you due credit.

**Comment by anseljh** [comment]
Cool. I don't need any special credit!
