### ISSUE TITLE
Suggestion: Rename "No Illegal Dealing in Securities"

### ISSUE THREAD

**Issue by anseljh** [rxnda/rxnda-forms#3]
Consider renaming "No Illegal Dealing in Securities" to "No Insider Trading". Why? 
* It's more colloquial.
* It's more specific. The NDA doesn't need to concern itself with broker-dealer registration, for example.
* It's more in keeping with the substance of the section, which is about trading on material, nonpublic information.

**Comment by kemitchell** [comment]
Thanks!

I wonder whether "insider trading" is colloquial. But I still get the feeling you're right.

**Comment by anseljh** [comment]
Not the end of the inquiry, but there's this: https://books.google.com/ngrams/graph?content=insider+trading%2Cillegal+dealing&year_start=1950&year_end=2008&corpus=15&smoothing=3&share=&direct_url=t1%3B%2Cinsider%20trading%3B%2Cc0%3B.t1%3B%2Cillegal%20dealing%3B%2Cc0

**Comment by kemitchell** [comment]
@anseljh: Just pushed commits for this one, as well.

Let's follow up at https://github.com/rxnda/rxnda-forms/issues/2 on getting you credited.
